import { useEffect, useState } from "react";
import Link from "@/components/router-link";
import { ArrowRight, Target } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { PageError, PageLoading } from "@/components/feedback/page-state";
import { profileService } from "@/services/profile-service";
import type { PerfilFinanceiroPayload } from "@/types/api";

const vazio:PerfilFinanceiroPayload={salario_mensal:"0",outras_rendas:"0",meta_gasto_mensal:"0",dia_recebimento_salario:null,reserva_emergencia_atual:"0",meta_reserva_emergencia:"0",moeda:"BRL"};
export default function Page(){
 const[form,setForm]=useState(vazio);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[erro,setErro]=useState("");const[sucesso,setSucesso]=useState("");
 useEffect(()=>{profileService.buscar().then(p=>{if(p)setForm({salario_mensal:p.salario_mensal,outras_rendas:p.outras_rendas,meta_gasto_mensal:p.meta_gasto_mensal,dia_recebimento_salario:p.dia_recebimento_salario,reserva_emergencia_atual:p.reserva_emergencia_atual,meta_reserva_emergencia:p.meta_reserva_emergencia,moeda:p.moeda})}).catch(e=>setErro(e.message)).finally(()=>setLoading(false))},[]);
 const change=(k:keyof PerfilFinanceiroPayload,v:string)=>setForm(f=>({...f,[k]:k==="dia_recebimento_salario"?(v?Number(v):null):v}));
 async function salvar(e:React.FormEvent){e.preventDefault();setSaving(true);setErro("");try{await profileService.salvar(form);setSucesso("Configurações salvas com sucesso.")}catch(e){setErro(e instanceof Error?e.message:"Falha ao salvar.")}finally{setSaving(false)}}
 if(loading)return <PageLoading/>;
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Configuração financeira</h1><p className="text-sm text-slate-500">Defina sua renda e o limite mensal usado pelo semáforo e pelos alertas.</p></div>{erro&&<PageError mensagem={erro}/>} {sucesso&&<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300">{sucesso}</p>}<Card className="max-w-3xl"><form onSubmit={salvar} className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">Salário mensal<Input type="number" step="0.01" value={form.salario_mensal} onChange={e=>change("salario_mensal",e.target.value)}/></label><label className="grid gap-1 text-sm">Outras rendas<Input type="number" step="0.01" value={form.outras_rendas} onChange={e=>change("outras_rendas",e.target.value)}/></label><label className="grid gap-1 text-sm">Meta máxima de gastos no mês<Input type="number" step="0.01" value={form.meta_gasto_mensal} onChange={e=>change("meta_gasto_mensal",e.target.value)}/><span className="text-xs text-slate-500">Essa meta controla o semáforo, os alertas e o painel de incidentes.</span></label><label className="grid gap-1 text-sm">Dia do recebimento<Input type="number" min="1" max="31" value={form.dia_recebimento_salario??""} onChange={e=>change("dia_recebimento_salario",e.target.value)}/></label><Button type="submit" disabled={saving} className="sm:col-span-2 sm:justify-self-start">{saving?"Salvando...":"Salvar configurações"}</Button></form></Card><Card className="max-w-3xl border-blue-200 bg-blue-50 dark:border-blue-900 dark:bg-blue-950/30"><div className="flex gap-3"><Target className="mt-1 text-blue-500"/><div><h2 className="font-bold">Metas de reserva ficam em Metas</h2><p className="mt-1 text-sm text-slate-600 dark:text-[#c5d5e7]">A configuração guarda apenas o limite de gastos. Objetivos como reserva de emergência, viagem ou moto devem ser criados na página de metas. O local onde o dinheiro está guardado fica em Reservas e investimentos.</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/metas" className="inline-flex items-center gap-2 text-sm font-bold text-blue-600">Abrir metas <ArrowRight size={15}/></Link><Link href="/patrimonio" className="inline-flex items-center gap-2 text-sm font-bold text-blue-600">Abrir patrimônio <ArrowRight size={15}/></Link></div></div></div></Card></div>
}
